### ISSUE TITLE
__init__ takes no parameters error

### ISSUE THREAD

**Issue by vipercortex** [kivy-garden/garden.datetimepicker#7]
For the  following example with Python 3.6.5 Anaconda:

from kivy.app import App
from kivy.garden.datetimepicker import DatetimePicker
from kivy.garden.datetimepicker import TimePicker
class MyDateTimePickApp(App):
    def build(self):
        dtp = DatetimePicker()
        return dtp
MyDateTimePickApp().run()

I get the following error code:

Traceback (most recent call last):
   File "test_datetimepicker.py", line 16, in <module>
     MyDateTimePickApp().run()
   File "C:\Anaconda3\lib\site-packages\kivy\app.py", line 800, in run
     root = self.build()
   File "test_datetimepicker.py", line 12, in build
     dtp = DatetimePicker()
   File "C:\Users\jmangelschots\.kivy\garden\garden.datetimepicker\__init__.py", line 130, in __init__
     self.init_roulettes()
   File "C:\Users\jmangelschots\.kivy\garden\garden.datetimepicker\__init__.py", line 139, in init_roulettes
     self.second = second = TimeFormatCyclicRoulette(cycle=60, **kw)
   File "C:\Users\jmangelschots\.kivy\garden\garden.roulette\__init__.py", line 443, in __init__
     super(CyclicRoulette, self).__init__(**kw)
   File "C:\Users\jmangelschots\.kivy\garden\garden.roulette\__init__.py", line 336, in __init__
     super(Roulette, self).__init__(**kw)
   File "C:\Users\jmangelschots\.kivy\garden\garden.tickline\__init__.py", line 568, in __init__
     self.on_scroll_effect_cls()
   File "C:\Users\jmangelschots\.kivy\garden\garden.tickline\__init__.py", line 614, in on_scroll_effect_cls
     effect = self.scroll_effect = self.scroll_effect_cls(round_value=False)
   File "C:\Anaconda3\lib\site-packages\kivy\effects\kinetic.py", line 110, in __init__
     super(KineticEffect, self).__init__(**kwargs)
   File "kivy\_event.pyx", line 243, in kivy._event.EventDispatcher.__init__
 TypeError: object.__init__() takes no parameters

**Comment by vkrnt18** [comment]
I am also getting a similar error when tested as documented. Pls support:

$vim test_datetimepicker.py
-----------------------------------------------------------
from kivy.base import runTouchApp
from kivy.garden.datetimepicker import DatetimePicker

if __name__ == '__main__':
    from kivy.base import runTouchApp
    runTouchApp(DatetimePicker())
-----------------------------------------------------------

$ python test_datetimepicker.py 
[INFO   ] [Logger      ] Record log in /home/vkrnt18/.kivy/logs/kivy_18-11-26_61.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.0 (default, Oct  9 2018, 10:31:47) 
[GCC 7.3.0]
[INFO   ] [Factory     ] 194 symbols loaded
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: pygame
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 17.2.3'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) '>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "test_datetimepicker.py", line 7, in <module>
     runTouchApp(DatetimePicker())
   File "/home/vkrnt18/anaconda3/envs/kivy/lib/python3.7/site-packages/kivy/garden/datetimepicker/__init__.py", line 130, in __init__
     self.init_roulettes()
   File "/home/vkrnt18/anaconda3/envs/kivy/lib/python3.7/site-packages/kivy/garden/datetimepicker/__init__.py", line 139, in init_roulettes
     self.second = second = TimeFormatCyclicRoulette(cycle=60, **kw)
   File "/home/vkrnt18/anaconda3/envs/kivy/lib/python3.7/site-packages/kivy/garden/roulette/__init__.py", line 443, in __init__
     super(CyclicRoulette, self).__init__(**kw)
   File "/home/vkrnt18/anaconda3/envs/kivy/lib/python3.7/site-packages/kivy/garden/roulette/__init__.py", line 336, in __init__
     super(Roulette, self).__init__(**kw)
   File "/home/vkrnt18/anaconda3/envs/kivy/lib/python3.7/site-packages/kivy/garden/tickline/__init__.py", line 568, in __init__
     self.on_scroll_effect_cls()
   File "/home/vkrnt18/anaconda3/envs/kivy/lib/python3.7/site-packages/kivy/garden/tickline/__init__.py", line 614, in on_scroll_effect_cls
     effect = self.scroll_effect = self.scroll_effect_cls(round_value=False)
   File "/home/vkrnt18/anaconda3/envs/kivy/lib/python3.7/site-packages/kivy/effects/kinetic.py", line 110, in __init__
     super(KineticEffect, self).__init__(**kwargs)
   File "kivy/_event.pyx", line 243, in kivy._event.EventDispatcher.__init__
 TypeError: object.__init__() takes no arguments

**Comment by oceanlazy** [comment]
Same issue not work

**Comment by smaudet** [comment]
Trivial to fix...

Maybe I'll post a patch.

However, I'm going to say, this is not really worth the effort perhaps, the UX is fairly bad (quite small and doesn't really handle sizing well).
